export const projects = [
  {
    title: 'CLI App',
    description: "This application allows user to experience the Command Line Interface by using several tools such as File Directory System, Book Search Tool, Currency Convert Tool, and Math Tool. Please visit the github link (Click Code) for more details.",
    image: '/images/cli.jpg',
    tags: ['React'],
    hashtags: ['OOP', 'Linked List', 'API'],
    source: 'https://github.com/tkwonn/cli-app',
    visit: 'https://cli-app.vercel.app/',
    id: 0,
  },
  {
    title: 'Computer Builder',
    description: "In this app, users would select major parts of the computer to build their own computer. It uses API to retrieve data in an asynchronous process. Depending on each component chosen by the user, it will calculate the specs of the computer and compare whether it is better for work or gaming. Through this project, I learned how to handle the use of JSON and Promise Object, how to use lambda function and APIs for asynchrounous data fetching.",
    image: '/images/computer.jpg',
    tags: ['React', 'TailwindCSS'],
    hashtags: [],
    source: 'https://github.com/tkwonn/computer-builder',
    visit: 'https://tkwonn.github.io/computer-builder/',
    id: 1,
  },
  {
    title: 'Clicker Empire Game',
    description: "This is an app where the user can earn money by clicking on hamburgers, and use the money to upgrade, invest, or buy real estate. This was a good learning opportunity for me to get used to the DOM operations.",
    image: '/images/clicker.jpg',
    tags: ['JavaScript', 'Bootstrap'],
    hashtags: [],
    source: 'https://github.com/tkwonn/Clicker_Empire_Game',
    visit: 'https://clicker-empire-game-five.vercel.app/',
    id: 2,
  },
  {
    title: 'Task Management App',
    description: "This app allows users to manage projects and tasks visually using the board. One board represents one project and contains one or more lists. User can drag-n-drop to change the order of lists, the order of tasks inside the list, and move task from one list to another as well. I learned how to implement simple CRUD functionality by creating this app.",
    image: '/images/task.png',
    tags: ['Vue'],
    hashtags: [],
    source: 'https://github.com/tkwonn/task-management-app',
    visit: 'https://task-management-app-snowy.vercel.app/',
    id: 3,
  },
  {
    title: 'Vending Machine',
    description: "This app uses a slider to implement a function that allows users to purchase products by selecting a number, just like a vending machine. In this project, I learned what a DOM is and how to manipulate it in JavaScript, and also learned how to use event listeners to process data through actions in the interface.",
    points: "",
    image: '/images/vending.jpg',
    tags: ['JavaScript', 'Bootstrap'],
    hashtags: [],
    source: 'https://github.com/tkwonn/Vending_Machine',
    visit: 'https://vending-machine-five.vercel.app/',
    id: 4,
  },
  {
    title: 'Battery Finder Program',
    description: "This app allows users to enter the brand, model, and power consumption of the camera. Once the user has made the selections, it will automatically present a list of the most suitable batteries. In this project, I learned how to manipulate a DOM and how to change the elements to be displayed based on user inputs.",
    points: "",
    image: '/images/battery.jpg',
    tags: ['JavaScript', 'Bootstrap'],
    hashtags: [],
    source: 'https://github.com/tkwonn/Battery_Finder_Program',
    visit: 'https://battery-finder-program-omega.vercel.app/',
    id: 5,
  },
];
