export const projects = [
  {
    title: 'Computer Builder',
    description: "CPU、GPUなどコンピュータの主要な部品を選択しPCを作ります。選択した部品のベンチマークをもとにゲーミング用と作業用のスコアを算出し、スペックを比較するアプリです。",
    points: "useContextとuseReducerを使用した状態管理、actionのタイプを定数にし別のファイルで管理しました。",
      image: '/images/computer.jpg',
      tags: ['React', 'TailwindCSS'],
    source: 'https://github.com/tkwonn/computer-builder',
    visit: 'https://tkwonn.github.io/computer-builder/',
    id: 0,
  },
  {
    title: 'Clicker Empire Game',
    description: "ハンバーガーをクリックしてお金を稼ぎ、稼いだお金で株や不動産などを購入して億万長者へと成長していくシミュレーションゲームです。",
    points: "ゲームの設定が特有なため、遊び方をモーダルウィンドウで表示するようにしました。また、ゲームのデータをローカルストレージに保存したり、データをリセットできる機能をつけました。",
      image: '/images/clicker.jpg',
      tags: ['JavaScript', 'Bootstrap'],
    source: 'https://github.com/tkwonn/Clicker_Empire_Game',
    visit: 'https://clicker-empire-game-five.vercel.app/',
    id: 2,
  },
  {
    title: 'Task Management App',
    description: "カンバン方式のタスク管理アプリです。Trelloのようにリスト毎にタスクを追加、削除、編集することができます。また、ユーザーはドラッグ・アンド・ドロップでリストの順番やリスト内のタスクの順番を変更したり、リストから別のリストにタスクを移動したりすることができます。",
    points: "ドラッグ・アンド・ドロップで移動したリストやタスク、追加・編集した内容をローカルストレージに保存するようにしました。デザインにもこだわりました。",
    image: '/images/task.png',
    tags: ['Vue'],
    source: 'https://github.com/tkwonn/task-management-app',
    visit: 'https://task-management-app-snowy.vercel.app/',
    id: 3,
  },
  {
    title: 'Vending Machine',
    description: "ボタンの番号をクリックすると商品の画像が詳細とともにスライダーで表示されるアプリです。",
    points: "通常の自動販売機にはない機能として商品の詳細をコメントで表示するようにしました。",
    image: '/images/vending.jpg',
    tags: ['JavaScript', 'Bootstrap'],
    source: 'https://github.com/tkwonn/Vending_Machine',
    visit: 'https://vending-machine-five.vercel.app/',
    id: 4,
  },
  {
    title: 'Battery Finder Program',
    description: "カメラのブランド、モデル、アクセサリの消費電力を入力すると、自動で最適なバッテリーの一覧を確認することができるアプリです。",
    points: "ユーザインターフェースと内部のデータを分けるMVCモデルに沿った設計を意識しました。",
    image: '/images/battery.jpg',
    tags: ['JavaScript', 'Bootstrap'],
    source: 'https://github.com/tkwonn/Battery_Finder_Program',
    visit: 'https://battery-finder-program-omega.vercel.app/',
    id: 5,
  },
];
