name: deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run check-format

  deploy:
    needs: lint-and-format
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install PM2
        run: npm install pm2 -g

      - name: Set up SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: ${{ secrets.EC2_HOST }}

      - name: Deploy to EC2 server
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          pm2 deploy ecosystem.config.js production --force
